### ISSUE TITLE
grep command injection

### ISSUE THREAD

**Issue by LeDevDuDimanche** [poechsel/gazon#13]
https://github.com/poechsel/gazon/blob/b93d5803799660a82574c3ba6b6674396841cf23/src/common/commands/grep.cpp#L104-L109

How:
                login KevinMitnick
                pass FreeKevin
                grep gonna_get_hacked';gnome-calculator;'
Why:
        the grep command that is executed by the server is created like the following
            std::string cmd = "cd " + context.getAbsolutePath().string() +
                "; grep -Rl --exclude-dir=" + Config::temp_directory +
                " -E '" + pattern + "' * | sort";

        what we can manipulate is the pattern. One sees that we can close the single quote starting
        after the -E argument by passing gonna_get_hacked', we could also simpy provide ' as argument
        instead of making jokes. Then we add a semicolon stating that the shell must interpret
        the next command. Here we decide that the next argument is simply gnome-calculator. Then we add a semicolon to say to the shell that it has to interpret the next command. Since there is another single quote following that, we need to pair it with another single quote, otherwise the shell will wait for an indefinite amount of time for the single quote to be paired, thus having no command executed in the end.
        In the end, this will execute a cd, a recursive grep with an empty pattern, followed by an execution of gnome-calculator. The fact that next command crashes or not doesnt matter.

**Comment by LeDevDuDimanche** [comment]
Duplicate of https://github.com/poechsel/gazon/issues/12
But since we have to create issue anyway..

**Comment by poechsel** [comment]
Closing as it is a duplicate
